[workspace]
resolver = "2"
members = ["crates/quosh-proto", "crates/quosh-predict", "crates/quosh-server", "crates/quosh-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
repository = "https://github.com/jt/quosh"

[workspace.dependencies]
quosh-proto = { path = "crates/quosh-proto" }
quosh-predict = { path = "crates/quosh-predict" }
anyhow = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lz4_flex = { version = "0.13", default-features = false, features = ["std"] }
hex = "0.4"
rand = "0.9"
vte = "0.15"
unicode-width = "0.2"
bytes = "1"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
blit-remote = { git = "https://github.com/indent-com/blit", package = "blit-remote", rev = "7ec6085c54430f003fbafa7542613c46994c09c8" }
blit-alacritty = { git = "https://github.com/indent-com/blit", package = "blit-alacritty", rev = "7ec6085c54430f003fbafa7542613c46994c09c8" }
